name: Release library

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-library:
    if: github.repository == 'hsorby/tomathml'
    runs-on: ubuntu-24.04
    name: Release package
    permissions:
      contents: write
    steps:
      - name: Create Release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ github.ref_name }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${{ github.ref_name }}" \
              --generate-notes
