name: Run Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - main

jobs:
  run_tests:
    name: Configure, build, and test on ${{ matrix.os.nm }} with python ${{ matrix.py }}
    runs-on: ${{ matrix.os.nm }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # - nm: ubuntu-latest
            # gn: Unix Makefiles
          # - nm: macos-13
            # gn: Xcode
          # - nm: macos-latest
            # gn: Unix Makefiles
          - nm: windows-latest
            gn: Visual Studio 17 2022
        py: ['3.13']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
          python-version: ${{ matrix.py }}
    - name: Install nanobind
      run: |
        pip install nanobind
    - name: Install Doxygen if not Windows
      if: runner.os != 'Windows'
      shell: bash
      run: |
        bash .github/scripts/install_doxygen.sh
    - name: Install Doxygen if Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        .github/scripts/install_doxygen.ps1
    - name: Configure
      run: |
        cmake -S . -B build -G "${{ matrix.os.gn }}"
    - name: Build
      run: |
        cd build
        cmake --build . --config Release
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
    - name: Test
      run: |
        cd build
        ctest
    # - uses: purpleKarrot/cmake-action@master
    #   with:
    #     cmake-generator: ${{ matrix.os.gn }}
