name: Test Release Trigger

on:
  release:
    types: [published, created]

jobs:
  print:
    name: Some name
    runs-on: ubuntu-latest
    steps:
      - name: Echo release info
        run: |
          echo "Triggered by release: ${{ github.event.release.tag_name }}"
