name: Test Release Trigger

on:
  release:
    types: [published, created]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by release: ${{ github.event.release.tag_name }}"
